### ISSUE TITLE
[Unlikely Potential Bug] Equipment Drones Have Constant HP Drain

### ISSUE THREAD

**Issue by VaelophisNyx** [Moffein/NoVoidAllies#1]
I posted the bug over here https://github.com/William758/ZetTweaks/issues/9 since it might be more likely that it's that mod, given that it directly alters Equipment Drone spawning code, but figured I'd cross-post this bug here too on the off chance that it might be your mod?

Fantastic mod btw, makes Captain and Engineer genuinely more playable.

**Comment by Moffein** [comment]
Glad to hear you're enjoying the mod!
It's unlikely that this is causing the bug since this mod only touches the Void Infestor's Infestation skill state.

**Comment by VaelophisNyx** [comment]
Yeah it turns out it was a debug feature that got left in on the linked mod.
